# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1100, 830)
        Form.setMinimumSize(QtCore.QSize(1100, 830))
        Form.setMaximumSize(QtCore.QSize(1100, 830))
        Form.setStyleSheet("background-color: rgb(62, 62, 62);")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 110, 651, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(640, 480))
        self.label.setMaximumSize(QtCore.QSize(640, 480))
        self.label.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(10)
        self.label.setMidLineWidth(10)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.photo = QtWidgets.QLabel(Form)
        self.photo.setGeometry(QtCore.QRect(720, 120, 331, 200))
        self.photo.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.photo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.photo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.photo.setLineWidth(10)
        self.photo.setMidLineWidth(10)
        self.photo.setText("")
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.face = QtWidgets.QLabel(Form)
        self.face.setGeometry(QtCore.QRect(720, 340, 330, 250))
        self.face.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.face.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.face.setText("")
        self.face.setScaledContents(True)
        self.face.setObjectName("face")
        self.status = QtWidgets.QLabel(Form)
        self.status.setGeometry(QtCore.QRect(60, 660, 431, 91))
        self.status.setStyleSheet("font: 36pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.checkin_status = QtWidgets.QLabel(Form)
        self.checkin_status.setGeometry(QtCore.QRect(60, 30, 991, 61))
        self.checkin_status.setStyleSheet("font: 36pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.checkin_status.setTextFormat(QtCore.Qt.AutoText)
        self.checkin_status.setAlignment(QtCore.Qt.AlignCenter)
        self.checkin_status.setObjectName("checkin_status")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(760, 630, 271, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.idcard = QtWidgets.QLabel(self.formLayoutWidget)
        self.idcard.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.idcard.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.idcard.setObjectName("idcard")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.idcard)
        self.idcard_checkin = QtWidgets.QLabel(self.formLayoutWidget)
        self.idcard_checkin.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.idcard_checkin.setAlignment(QtCore.Qt.AlignCenter)
        self.idcard_checkin.setObjectName("idcard_checkin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idcard_checkin)
        self.name = QtWidgets.QLabel(self.formLayoutWidget)
        self.name.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name.setObjectName("name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.name)
        self.time = QtWidgets.QLabel(self.formLayoutWidget)
        self.time.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.time.setObjectName("time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.time)
        self.time_checkin = QtWidgets.QLabel(self.formLayoutWidget)
        self.time_checkin.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.time_checkin.setAlignment(QtCore.Qt.AlignCenter)
        self.time_checkin.setObjectName("time_checkin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.time_checkin)
        self.date = QtWidgets.QLabel(self.formLayoutWidget)
        self.date.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.date.setObjectName("date")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.date)
        self.date_checkin = QtWidgets.QLabel(self.formLayoutWidget)
        self.date_checkin.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.date_checkin.setAlignment(QtCore.Qt.AlignCenter)
        self.date_checkin.setObjectName("date_checkin")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.date_checkin)
        self.name_checkin = QtWidgets.QLabel(self.formLayoutWidget)
        self.name_checkin.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.name_checkin.setAlignment(QtCore.Qt.AlignCenter)
        self.name_checkin.setObjectName("name_checkin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_checkin)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(510, 610, 185, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.idcardread = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.idcardread.setFont(font)
        self.idcardread.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.idcardread.setIconSize(QtCore.QSize(16, 16))
        self.idcardread.setObjectName("idcardread")
        self.verticalLayout_3.addWidget(self.idcardread)
        self.facerec = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.facerec.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.facerec.setObjectName("facerec")
        self.verticalLayout_3.addWidget(self.facerec)
        self.idcardandfacerec = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.idcardandfacerec.setStyleSheet("font: 16pt \"Leelawadee UI\";\n"
"color: rgb(255, 255, 255);")
        self.idcardandfacerec.setObjectName("idcardandfacerec")
        self.verticalLayout_3.addWidget(self.idcardandfacerec)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.status.setText(_translate("Form", "สถานะ"))
        self.checkin_status.setText(_translate("Form", "กรุณาเลือกสถานะ"))
        self.idcard.setText(_translate("Form", "บัตรประชาชน :"))
        self.idcard_checkin.setText(_translate("Form", "-"))
        self.name.setText(_translate("Form", "ชื่อ :"))
        self.time.setText(_translate("Form", "เวลาที่เข้า :"))
        self.time_checkin.setText(_translate("Form", "-"))
        self.date.setText(_translate("Form", "วันที่ :"))
        self.date_checkin.setText(_translate("Form", "-"))
        self.name_checkin.setText(_translate("Form", "-"))
        self.idcardread.setText(_translate("Form", "สแกนเฉพาะบัตร"))
        self.facerec.setText(_translate("Form", "สแกนเฉพาะใบหน้า"))
        self.idcardandfacerec.setText(_translate("Form", "สแกนบัตรและใบหน้า"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
